import React, { useState, useEffect } from 'react';
import { fetchCompanyData, analyzeRegulatoryStatus } from '../utils/sst-engine';
import { saveClient, getClientByCNPJ, saveClientIntake, updateAutoGenerated } from '../utils/storage';
import { generateCompleteData } from '../utils/AutomaticEngine';
import { getSuggestedRoles } from '../utils/RoleSuggester';

const ClientIntakeForm = ({ companyCNPJ, onComplete }) => {
    const [step, setStep] = useState(1);
    const [loading, setLoading] = useState(false);

    // Form data
    const [cnpj, setCnpj] = useState(companyCNPJ || '');
    const [companyData, setCompanyData] = useState(null);
    const [employeeCount, setEmployeeCount] = useState('');
    const [sectorsSelected, setSectorsSelected] = useState([]);
    const [rolesText, setRolesText] = useState('');
    const [activitiesSelected, setActivitiesSelected] = useState([]);
    const [photos, setPhotos] = useState([]);
    const [suggestedRoles, setSuggestedRoles] = useState([]);

    // Auto-load company data if CNPJ is provided as prop
    useEffect(() => {
        const loadCompanyData = async () => {
            if (companyCNPJ && !companyData) {
                console.log('[ClientIntakeForm] companyCNPJ prop provided:', companyCNPJ);
                setLoading(true);

                try {
                    const existing = await getClientByCNPJ(companyCNPJ);
                    if (existing) {
                        console.log('[ClientIntakeForm] Company data loaded:', existing);
                        setCompanyData(existing);
                        setCnpj(companyCNPJ);
                        setStep(2); // Skip step 1 (CNPJ input)
                    }
                } catch (error) {
                    console.error('[ClientIntakeForm] Error loading company data:', error);
                } finally {
                    setLoading(false);
                }
            }
        };

        loadCompanyData();
    }, [companyCNPJ, companyData]);


    // Update suggested roles when company data changes
    useEffect(() => {
        if (companyData?.cnae_desc) {
            setSuggestedRoles(getSuggestedRoles(companyData.cnae_desc));
        }
    }, [companyData]);


    const sectorOptions = [
        'Administrativo/Escritório',
        'Vendas/Comercial',
        'Produção/Fábrica',
        'Manutenção/Oficina',
        'Logística/Estoque',
        'Atendimento/Recepção',
        'Outro'
    ];

    const activityOptions = [
        { value: 'Computadores', label: 'Trabalho com Computadores/Escritório' },
        { value: 'Máquinas', label: 'Máquinas/Equipamentos Pesados' },
        { value: 'Químicos', label: 'Produtos Químicos' },
        { value: 'Altura', label: 'Trabalho em Altura' },
        { value: 'Veículos', label: 'Condução de Veículos' },
        { value: 'Atendimento', label: 'Atendimento ao Público' },
        { value: 'Confined', label: 'Espaço Confinado (NR-33)' },
        { value: 'Eletricidade', label: 'Eletricidade (NR-10)' }
    ];

    const [regStatus, setRegStatus] = useState(null);
    const [hasAgents, setHasAgents] = useState(null); // 'yes' or 'no'

    useEffect(() => {
        if (companyData) {
            const status = analyzeRegulatoryStatus(companyData);
            setRegStatus(status);
            // Reset agent verification on new company
            setHasAgents(null);
        }
    }, [companyData]);

    const handleSearchCNPJ = async () => {
        if (cnpj.replace(/\D/g, '').length !== 14) {
            alert('CNPJ inválido');
            return;
        }

        setLoading(true);

        try {
            // Check if company exists in Supabase
            console.log('[ClientIntakeForm] Checking if company exists:', cnpj);
            const existing = await getClientByCNPJ(cnpj);
            console.log('[ClientIntakeForm] Existing company:', existing);

            if (existing) {
                setCompanyData(existing);
                setStep(2);
                setLoading(false);
                return;
            }

            // Fetch from BrasilAPI and save to Supabase
            console.log('[ClientIntakeForm] Fetching from BrasilAPI...');
            const data = await fetchCompanyData(cnpj);
            console.log('[ClientIntakeForm] Data from BrasilAPI:', data);

            if (data) {
                setCompanyData(data);

                // Save to Supabase
                console.log('[ClientIntakeForm] Saving to Supabase...');
                const saveResult = await saveClient(data);
                console.log('[ClientIntakeForm] Save result:', saveResult);

                if (saveResult && saveResult.success && saveResult.data) {
                    console.log('[ClientIntakeForm] Saved company successfully:', saveResult.data);
                    setCompanyData(saveResult.data);
                } else {
                    console.error('[ClientIntakeForm] Failed to save company:', saveResult);
                    alert('⚠️ Empresa encontrada, mas houve erro ao salvar no banco. Continue o cadastro mesmo assim.');
                    setCompanyData(data);
                }

                setStep(2);
            } else {
                alert('CNPJ não encontrado. Verifique e tente novamente.');
            }
        } catch (error) {
            console.error('[ClientIntakeForm] Error in handleSearchCNPJ:', error);
            alert('Erro: ' + error.message);
        } finally {
            setLoading(false);
        }
    };

    const toggleSector = (sector) => {
        if (sectorsSelected.includes(sector)) {
            setSectorsSelected(sectorsSelected.filter(s => s !== sector));
        } else {
            setSectorsSelected([...sectorsSelected, sector]);
        }
    };

    const toggleActivity = (activity) => {
        if (activitiesSelected.includes(activity)) {
            setActivitiesSelected(activitiesSelected.filter(a => a !== activity));
        } else {
            setActivitiesSelected([...activitiesSelected, activity]);
        }
    };

    const handleComplete = async () => {
        // Validation for Regulatory Check
        if (regStatus?.recommendation === 'PGR_SIMPLIFIED' && hasAgents === null) {
            alert('⚠️ Por favor, responda à Verificação de Agentes (Sim ou Não) antes de continuar.');
            return;
        }

        setLoading(true);

        try {
            // Determine Final PGR Type
            const isSimplifiedEligible = regStatus?.recommendation === 'PGR_SIMPLIFIED';
            const finalPgrType = (isSimplifiedEligible && hasAgents === 'no') ? 'SIMPLIFIED' : 'FULL';

            // Salvar dados do formulário
            const intakeData = {
                employee_count: parseInt(employeeCount),
                sectors_selected: sectorsSelected,
                roles_text: rolesText,
                activities_selected: activitiesSelected,
                photos: photos,
                cnae: companyData.cnae,
                cnae_desc: companyData.cnae_desc,
                cnaes_secundarios: companyData.cnaes_secundarios || [],
                // Regulatory Data
                pgr_type: finalPgrType,
                nr1_verification: {
                    eligible: isSimplifiedEligible,
                    has_agents: hasAgents,
                    risk_degree: regStatus?.grau_risco
                }
            };

            const intakeResult = await saveClientIntake(companyData, intakeData);
            if (!intakeResult.success) {
                throw new Error(intakeResult.error);
            }

            // Gerar dados automaticamente
            const autoGenerated = generateCompleteData(companyData.cnpj, intakeData);
            const autoResult = await updateAutoGenerated(companyData, autoGenerated);

            if (!autoResult.success) {
                throw new Error(autoResult.error);
            }

            setLoading(false);

            // Mostrar mensagem de sucesso (Customizada por tipo)
            const docTypeMsg = finalPgrType === 'SIMPLIFIED' ? 'Declaração de Inexistência de Risco (DIR)' : 'PGR e PCMSO Completos';
            alert(`✅ Dados recebidos com sucesso!\n\nCom base na análise NR-1, geraremos: ${docTypeMsg}.\n\nVocê receberá um email em breve.`);

            // Always use companyCNPJ prop (passed from App.jsx)
            const finalCNPJ = companyCNPJ || companyData?.cnpj || cnpj;
            console.log('[ClientIntakeForm] Calling onComplete with CNPJ:', finalCNPJ);
            console.log('[ClientIntakeForm] companyCNPJ prop:', companyCNPJ);
            console.log('[ClientIntakeForm] companyData.cnpj:', companyData?.cnpj);
            console.log('[ClientIntakeForm] cnpj state:', cnpj);
            if (onComplete) onComplete(finalCNPJ, { workflow_status: 'analysis_in_progress' });
        } catch (error) {
            setLoading(false);
            alert('❌ Erro ao salvar dados: ' + error.message);
            console.error('Error saving intake:', error);
        }
    };

    return (
        <div style={{ maxWidth: '800px', margin: '0 auto', padding: '2rem' }}>
            {/* Header */}
            <div style={{ textAlign: 'center', marginBottom: '2rem' }}>
                <h1 style={{ color: 'var(--primary)', marginBottom: '0.5rem' }}>🏢 Cadastro Rápido - PGR/PCMSO</h1>
                <p style={{ color: '#64748b' }}>Preencha os dados abaixo (5-10 minutos)</p>

                {/* Progress indicator */}
                <div style={{ display: 'flex', justifyContent: 'center', gap: '10px', marginTop: '1.5rem' }}>
                    {[1, 2, 3, 4, 5].map(num => (
                        <div key={num} style={{
                            width: '40px',
                            height: '40px',
                            borderRadius: '50%',
                            background: step >= num ? 'var(--primary)' : '#e2e8f0',
                            color: step >= num ? 'white' : '#94a3b8',
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            fontWeight: 'bold',
                            transition: 'all 0.3s'
                        }}>
                            {num}
                        </div>
                    ))}
                </div>
            </div>

            {/* Step 1: CNPJ */}
            {step === 1 && (
                <div className="form-card">
                    <h2>1️⃣ Qual o CNPJ da empresa?</h2>
                    <div style={{ display: 'flex', gap: '10px', marginTop: '1rem' }}>
                        <input
                            type="text"
                            placeholder="00.000.000/0000-00"
                            value={cnpj}
                            onChange={(e) => setCnpj(e.target.value)}
                            style={{ flex: 1, padding: '1rem', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '1.1rem' }}
                            onKeyPress={(e) => e.key === 'Enter' && handleSearchCNPJ()}
                        />
                        <button
                            onClick={handleSearchCNPJ}
                            className="btn-primary"
                            disabled={loading}
                            style={{ padding: '1rem 2rem', fontSize: '1.1rem' }}
                        >
                            {loading ? '🔍 Buscando...' : '🔍 Buscar'}
                        </button>
                    </div>
                    {companyData && (
                        <div style={{ marginTop: '1rem', padding: '1rem', background: '#f0fdf4', border: '1px solid #86efac', borderRadius: '8px' }}>
                            <p style={{ color: '#15803d', fontWeight: 'bold' }}>✓ Empresa encontrada:</p>
                            <p style={{ color: '#166534', fontWeight: 'bold', fontSize: '1.1rem' }}>{companyData.name}</p>

                            <div style={{ marginTop: '0.8rem' }}>
                                <p style={{ color: '#15803d', fontSize: '0.85rem', fontWeight: 'bold' }}>Atividade Principal:</p>
                                <p style={{ color: '#166534', fontSize: '0.9rem' }}>{companyData.cnae} - {companyData.cnae_desc}</p>
                            </div>

                            {companyData.cnaes_secundarios && companyData.cnaes_secundarios.length > 0 && (
                                <div style={{ marginTop: '0.8rem', borderTop: '1px dashed #86efac', paddingTop: '0.5rem' }}>
                                    <p style={{ color: '#15803d', fontSize: '0.85rem', fontWeight: 'bold' }}>
                                        Atividades Secundárias ({companyData.cnaes_secundarios.length}):
                                    </p>
                                    <ul style={{ margin: '0.5rem 0 0 1.2rem', padding: 0, color: '#166534', fontSize: '0.85rem' }}>
                                        {companyData.cnaes_secundarios.slice(0, 3).map((sec, idx) => (
                                            <li key={idx} style={{ marginBottom: '4px' }}>{sec.codigo} - {sec.descricao}</li>
                                        ))}
                                        {companyData.cnaes_secundarios.length > 3 && (
                                            <li style={{ fontStyle: 'italic', opacity: 0.8 }}>... e mais {companyData.cnaes_secundarios.length - 3} atividades.</li>
                                        )}
                                    </ul>
                                </div>
                            )}
                        </div>
                    )}

                    {/* REGULATORY ANALYSIS MODULE */}
                    {regStatus && (
                        <div style={{ marginTop: '1rem', padding: '1rem', background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '8px' }}>
                            <h4 style={{ margin: '0 0 0.5rem 0', color: '#1e293b', fontSize: '0.95rem' }}>📋 Análise de Enquadramento (NR-1)</h4>

                            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '0.5rem' }}>
                                <span style={{
                                    background: regStatus.recommendation === 'PGR_SIMPLIFIED' ? '#dcfce7' : '#fee2e2',
                                    color: regStatus.recommendation === 'PGR_SIMPLIFIED' ? '#166534' : '#991b1b',
                                    padding: '2px 8px', borderRadius: '4px', fontSize: '0.8rem', fontWeight: 'bold'
                                }}>
                                    {regStatus.recommendation === 'PGR_SIMPLIFIED' ? 'ELEGÍVEL SIMPLIFICADO (ME/EPP + Risco 1/2)' : 'PGR COMPLETO (Obrigatório)'}
                                </span>
                                <span style={{ fontSize: '0.8rem', color: '#64748b' }}>Grau de Risco: {regStatus.grau_risco}</span>
                            </div>

                            <p style={{ fontSize: '0.85rem', color: '#475569', marginBottom: '1rem', lineHeight: '1.4' }}>
                                {regStatus.description}
                            </p>

                            {/* VERIFICAÇÃO DE EXPOSIÇÃO (Mandatory for Simplified) */}
                            {regStatus.recommendation === 'PGR_SIMPLIFIED' && (
                                <div style={{ marginTop: '0.8rem', borderTop: '1px solid #e2e8f0', paddingTop: '0.8rem' }}>
                                    <p style={{ fontSize: '0.9rem', fontWeight: 'bold', color: '#0f172a', marginBottom: '0.5rem' }}>
                                        ⚠️ Verificação de Agentes (NR-1.8.4):
                                    </p>
                                    <p style={{ fontSize: '0.85rem', color: '#475569', marginBottom: '0.8rem' }}>
                                        Existem agentes físicos (ruído, calor), químicos ou biológicos no ambiente de trabalho?
                                    </p>

                                    <div style={{ display: 'flex', gap: '1rem', marginBottom: '0.5rem' }}>
                                        <div onClick={() => setHasAgents('no')}
                                            style={{
                                                padding: '8px 12px', borderRadius: '6px', border: hasAgents === 'no' ? '2px solid #166534' : '1px solid #cbd5e1',
                                                background: hasAgents === 'no' ? '#dcfce7' : '#fff', cursor: 'pointer', flex: 1, textAlign: 'center'
                                            }}>
                                            <span style={{ fontSize: '0.9rem', color: hasAgents === 'no' ? '#166534' : '#64748b', fontWeight: hasAgents === 'no' ? 'bold' : 'normal' }}>Não (Manter Simplificado)</span>
                                        </div>

                                        <div onClick={() => setHasAgents('yes')}
                                            style={{
                                                padding: '8px 12px', borderRadius: '6px', border: hasAgents === 'yes' ? '2px solid #b91c1c' : '1px solid #cbd5e1',
                                                background: hasAgents === 'yes' ? '#fee2e2' : '#fff', cursor: 'pointer', flex: 1, textAlign: 'center'
                                            }}>
                                            <span style={{ fontSize: '0.9rem', color: hasAgents === 'yes' ? '#b91c1c' : '#64748b', fontWeight: hasAgents === 'yes' ? 'bold' : 'normal' }}>Sim (Exige Completo)</span>
                                        </div>
                                    </div>

                                    {hasAgents === 'yes' && (
                                        <div style={{ fontSize: '0.8rem', color: '#b91c1c', background: '#fef2f2', padding: '8px', borderRadius: '4px', border: '1px dashed #fca5a5' }}>
                                            🚨 <strong>Atenção:</strong> A presença de agentes nocivos exige a elaboração do PGR Completo, independente do porte ou grau de risco.
                                        </div>
                                    )}
                                    {hasAgents === 'no' && (
                                        <div style={{ fontSize: '0.8rem', color: '#166534', background: '#f0fdf4', padding: '8px', borderRadius: '4px', border: '1px dashed #86efac' }}>
                                            ✅ <strong>Validado:</strong> A empresa está apta para a Declaração de Inexistência de Risco (DIR).
                                        </div>
                                    )}
                                </div>
                            )}
                        </div>
                    )}
                </div>
            )}

            {/* Step 2: Funcionários */}
            {step === 2 && (
                <div className="form-card">
                    <h2>2️⃣ Quantos funcionários?</h2>
                    <input
                        required
                        type="number"
                        placeholder="Ex: 12"
                        value={employeeCount}
                        onChange={(e) => setEmployeeCount(e.target.value)}
                        style={{ width: '200px', padding: '1rem', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '1.1rem', marginTop: '1rem' }}
                    />
                    <p style={{ color: '#64748b', fontSize: '0.9rem', marginTop: '0.5rem' }}>Número total de colaboradores</p>

                    <div style={{ marginTop: '2rem', display: 'flex', gap: '10px' }}>
                        <button onClick={() => setStep(1)} className="btn-secondary">‹ Voltar</button>
                        <button
                            onClick={() => employeeCount && setStep(3)}
                            className="btn-primary"
                            disabled={!employeeCount}
                        >
                            Próximo ›
                        </button>
                    </div>
                </div>
            )}

            {/* Step 3: Setores */}
            {step === 3 && (
                <div className="form-card">
                    <h2>3️⃣ Quais setores sua empresa possui?</h2>
                    <p style={{ color: '#64748b', marginBottom: '1rem' }}>Selecione todos que se aplicam:</p>

                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: '10px' }}>
                        {sectorOptions.map(sector => (
                            <div
                                key={sector}
                                onClick={() => toggleSector(sector)}
                                style={{
                                    padding: '1rem',
                                    border: sectorsSelected.includes(sector) ? '2px solid var(--primary)' : '1px solid #e2e8f0',
                                    borderRadius: '8px',
                                    cursor: 'pointer',
                                    background: sectorsSelected.includes(sector) ? '#f0f9ff' : 'white',
                                    transition: 'all 0.2s'
                                }}
                            >
                                <input
                                    type="checkbox"
                                    checked={sectorsSelected.includes(sector)}
                                    readOnly
                                    style={{ marginRight: '8px' }}
                                />
                                {sector}
                            </div>
                        ))}
                    </div>

                    <div style={{ marginTop: '2rem', display: 'flex', gap: '10px' }}>
                        <button onClick={() => setStep(2)} className="btn-secondary">‹ Voltar</button>
                        <button
                            onClick={() => sectorsSelected.length > 0 && setStep(4)}
                            className="btn-primary"
                            disabled={sectorsSelected.length === 0}
                        >
                            Próximo ›
                        </button>
                    </div>
                </div>
            )}

            {/* Step 4: Cargos */}
            {step === 4 && (
                <div className="form-card">
                    <h2>4️⃣ Principais cargos/funções</h2>
                    <p style={{ color: '#64748b', marginBottom: '1rem' }}>Liste os cargos separados por vírgula:</p>

                    {/* SUGESTÕES BLINDADAS */}
                    {suggestedRoles.length > 0 && (
                        <div style={{ marginBottom: '1rem', background: '#f8fafc', padding: '10px', borderRadius: '8px', border: '1px dashed #cbd5e1' }}>
                            <p style={{ fontSize: '0.85rem', color: '#64748b', marginBottom: '0.5rem', fontWeight: 'bold' }}>
                                ⚡ Sugestões para {companyData?.cnae_desc ? `"${companyData.cnae_desc.split(' ')[0]}..."` : 'seu ramo'} (clique para adicionar):
                            </p>
                            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
                                {suggestedRoles.map(role => (
                                    <button
                                        key={role}
                                        type="button"
                                        onClick={() => {
                                            if (!rolesText.includes(role)) {
                                                const separator = rolesText.trim().length > 0 && !rolesText.trim().endsWith(',') ? ', ' : '';
                                                setRolesText(prev => prev + separator + role);
                                            }
                                        }}
                                        style={{
                                            padding: '4px 12px',
                                            borderRadius: '20px',
                                            border: '1px solid #94a3b8',
                                            background: '#fff',
                                            color: '#334155',
                                            cursor: 'pointer',
                                            fontSize: '0.85rem',
                                            transition: 'all 0.2s',
                                            display: 'flex',
                                            alignItems: 'center',
                                            gap: '4px'
                                        }}
                                        onMouseOver={(e) => e.currentTarget.style.background = '#e2e8f0'}
                                        onMouseOut={(e) => e.currentTarget.style.background = '#fff'}
                                    >
                                        <span>+</span> {role}
                                    </button>
                                ))}
                            </div>
                        </div>
                    )}

                    <textarea
                        required
                        placeholder="Ex: Gerente, Vendedor, Assistente Administrativo, Operador de Máquinas"
                        value={rolesText}
                        onChange={(e) => setRolesText(e.target.value)}
                        style={{
                            width: '100%',
                            minHeight: '120px',
                            padding: '1rem',
                            border: '1px solid #e2e8f0',
                            borderRadius: '8px',
                            fontSize: '1rem',
                            fontFamily: 'inherit'
                        }}
                    />

                    <p style={{ color: '#64748b', fontSize: '0.9rem', marginTop: '0.5rem' }}>
                        💡 Dica: Não precisa ser técnico. Use nomes simples como "Vendedor", "Gerente", etc.
                    </p>

                    <div style={{ marginTop: '2rem', display: 'flex', gap: '10px' }}>
                        <button onClick={() => setStep(3)} className="btn-secondary">‹ Voltar</button>
                        <button
                            onClick={() => rolesText.trim() && setStep(5)}
                            className="btn-primary"
                            disabled={!rolesText.trim()}
                        >
                            Próximo ›
                        </button>
                    </div>
                </div>
            )}

            {/* Step 5: Atividades */}
            {step === 5 && (
                <div className="form-card">
                    <h2>5️⃣ Sua equipe trabalha com:</h2>
                    <p style={{ color: '#64748b', marginBottom: '1rem' }}>Marque todas as atividades realizadas:</p>

                    <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                        {activityOptions.map(activity => (
                            <div
                                key={activity.value}
                                onClick={() => toggleActivity(activity.value)}
                                style={{
                                    padding: '1rem',
                                    border: activitiesSelected.includes(activity.value) ? '2px solid var(--primary)' : '1px solid #e2e8f0',
                                    borderRadius: '8px',
                                    cursor: 'pointer',
                                    background: activitiesSelected.includes(activity.value) ? '#f0f9ff' : 'white',
                                    transition: 'all 0.2s'
                                }}
                            >
                                <input
                                    type="checkbox"
                                    checked={activitiesSelected.includes(activity.value)}
                                    readOnly
                                    style={{ marginRight: '8px' }}
                                />
                                {activity.label}
                            </div>
                        ))}
                    </div>

                    <div style={{ marginTop: '2rem', display: 'flex', gap: '10px' }}>
                        <button onClick={() => setStep(4)} className="btn-secondary">‹ Voltar</button>
                        <button
                            onClick={handleComplete}
                            className="btn-primary"
                            disabled={loading || activitiesSelected.length === 0}
                            style={{ background: '#10b981', flex: 1 }}
                        >
                            {loading ? '⏳ Gerando documentos...' : '✅ Enviar para Análise'}
                        </button>
                    </div>
                </div>
            )}

            <style>{`
                .form-card {
                    background: white;
                    padding: 2rem;
                    border-radius: 12px;
                    box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
                }
                .form-card h2 {
                    color: var(--primary);
                    margin-bottom: 1rem;
                }
            `}</style>
        </div>
    );
};

export default ClientIntakeForm;
