import { validateCA } from '../utils/EPIValidator';

// ... inside the component ...
const [caStatuses, setCaStatuses] = useState({});

useEffect(() => {
    const checkCAs = async () => {
        const statusMap = {};
        if (activeTab === 'epi' && localData.epis) {
            for (const epi of localData.epis) {
                if (epi.ca && epi.ca !== 'N/A') {
                    const status = await validateCA(epi.ca);
                    statusMap[epi.ca] = status;
                }
            }
            setCaStatuses(statusMap);
        }
    };
    checkCAs();
}, [activeTab, localData.epis]);

import { supabase } from '../utils/supabase';
import { updateAutoGenerated, getMedicalCoordinators, getTechnicalResponsibles, getReferenceHospitals, getCompanyProfessionals, assignProfessionalsToCompany } from '../utils/storage';
import { generateExamsFromRisks } from '../utils/AutomaticEngine';

const ReviewView = ({ companyData, autoGeneratedData, onSave, onBack }) => {
    const [activeTab, setActiveTab] = useState('risks');
    const [localData, setLocalData] = useState(autoGeneratedData);
    const [loading, setLoading] = useState(false);
    const [saving, setSaving] = useState(false);

    // EPI Validation State
    const [caStatuses, setCaStatuses] = useState({});

    // Effect to validate CAs when tab is 'epi'
    useEffect(() => {
        const checkCAs = async () => {
            if (activeTab === 'epi' && localData.epis) {
                const statusMap = {};
                for (const epi of localData.epis) {
                    if (epi.ca && epi.ca !== 'N/A') {
                        // Simply check against our local database in EPIValidator
                        // In a real app, this would be an async call to a backend
                        import('../utils/EPIValidator').then(module => {
                            module.validateCA(epi.ca).then(status => {
                                setCaStatuses(prev => ({ ...prev, [epi.ca]: status }));
                            });
                        });
                    }
                }
            }
        };
        checkCAs();
    }, [activeTab, localData.epis]);
    const [localInventory, setLocalInventory] = useState(autoGeneratedData.risks || []);

    const handleSave = () => {
        onSave(localData, localInventory);
    };

    const handleRecalculateExams = () => {
        if (window.confirm('Isso irá substituir a lista atual de exames pelas sugestões baseadas nos riscos atuais. Deseja continuar?')) {
            const newExams = generateExamsFromRisks(localInventory);
            setLocalData(prev => ({ ...prev, medical_exams: newExams }));
        }
    };

    const updateField = (section, index, field, value) => {
        const newData = { ...localData };
        newData[section][index][field] = value;
        setLocalData(newData);
    };

    const updateRisk = (index, field, value) => {
        const newInventory = [...localInventory];
        newInventory[index][field] = value;
        setLocalInventory(newInventory);
    };

    const inputStyle = {
        padding: '0.5rem',
        border: '1px solid #e2e8f0',
        borderRadius: '6px',
        fontSize: '0.9rem',
        width: '100%'
    };

    const sectionTitle = {
        fontSize: '1.1rem',
        fontWeight: 'bold',
        color: 'var(--primary)',
        marginTop: '1.5rem',
        marginBottom: '1rem',
        borderBottom: '2px solid #e2e8f0',
        paddingBottom: '0.5rem'
    };

    return (
        <div style={{ background: 'white', padding: '2rem', borderRadius: '1rem', boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1)' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
                <h2 style={{ margin: 0, color: 'var(--primary)' }}>✏️ Revisão de Dados</h2>
                <div style={{ display: 'flex', gap: '1rem' }}>
                    <button onClick={onCancel} className="btn-secondary">Cancelar</button>
                    <button onClick={handleSave} className="btn-primary">💾 Salvar Alterações</button>
                </div>
            </div>

            {/* TABS */}
            <div style={{ display: 'flex', gap: '1rem', borderBottom: '1px solid #e2e8f0', marginBottom: '2rem', overflowX: 'auto' }}>
                {['setores', 'cargos', 'riscos', 'exames', 'cronograma'].map(tab => (
                    <button
                        key={tab}
                        onClick={() => setActiveTab(tab)}
                        style={{
                            padding: '0.75rem 1.5rem',
                            background: 'transparent',
                            color: activeTab === tab ? 'var(--primary)' : '#64748b',
                            border: 'none',
                            borderBottom: activeTab === tab ? '2px solid var(--primary)' : 'none',
                            fontWeight: activeTab === tab ? '600' : '400',
                            cursor: 'pointer',
                            textTransform: 'capitalize'
                        }}
                    >
                        {tab === 'setores' && '🏢 Setores'}
                        {tab === 'cargos' && '👷 Cargos'}
                        {tab === 'riscos' && '⚠️ Inventário de Riscos'}
                        {tab === 'exames' && '🩺 Exames Médicos'}
                        {tab === 'cronograma' && '📅 Plano de Ação'}
                    </button>
                ))}
            </div>

            {/* CONTENT */}

            {activeTab === 'setores' && (
                <div>
                    <h3 style={sectionTitle}>Setores Identificados</h3>
                    {localData.sectors.map((sector, idx) => (
                        <div key={idx} style={{ padding: '1rem', background: '#f8fafc', borderRadius: '8px', marginBottom: '1rem' }}>
                            <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.85rem', color: '#64748b' }}>Nome do Setor</label>
                            <input
                                type="text"
                                value={sector.name}
                                onChange={(e) => updateField('sectors', idx, 'name', e.target.value)}
                                style={inputStyle}
                            />
                            <label style={{ display: 'block', marginTop: '1rem', marginBottom: '0.5rem', fontSize: '0.85rem', color: '#64748b' }}>Descrição do Ambiente</label>
                            <textarea
                                value={sector.description || ''}
                                onChange={(e) => updateField('sectors', idx, 'description', e.target.value)}
                                style={{ ...inputStyle, minHeight: '80px' }}
                                placeholder="Descreva o ambiente, iluminação, ventilação, piso, etc."
                            />
                        </div>
                    ))}
                    {localData.sectors.length === 0 && <p style={{ color: '#94a3b8', textAlign: 'center' }}>Nenhum setor identificado.</p>}
                </div>
            )}

            {activeTab === 'cargos' && (
                <div>
                    <h3 style={sectionTitle}>Cargos e Funções</h3>
                    {localData.roles.map((role, idx) => (
                        <div key={idx} style={{ padding: '1rem', background: '#f8fafc', borderRadius: '8px', marginBottom: '1rem' }}>
                            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                                <div>
                                    <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.85rem', color: '#64748b' }}>Nome do Cargo</label>
                                    <input
                                        type="text"
                                        value={role.name}
                                        onChange={(e) => updateField('roles', idx, 'name', e.target.value)}
                                        style={inputStyle}
                                    />
                                </div>
                                <div>
                                    <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.85rem', color: '#64748b' }}>CBO</label>
                                    <input
                                        type="text"
                                        value={role.cbo || ''}
                                        onChange={(e) => updateField('roles', idx, 'cbo', e.target.value)}
                                        style={inputStyle}
                                        placeholder="0000-00"
                                    />
                                </div>
                                <div style={{ gridColumn: '1 / -1' }}>
                                    <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.85rem', color: '#64748b' }}>Setor</label>
                                    <select
                                        value={role.sector_id || ''}
                                        onChange={(e) => updateField('roles', idx, 'sector_id', e.target.value)}
                                        style={inputStyle}
                                    >
                                        <option value="">Selecione um setor...</option>
                                        {localData.sectors.map(s => (
                                            <option key={s.id} value={s.id}>{s.name}</option>
                                        ))}
                                    </select>
                                </div>
                                <div style={{ gridColumn: '1 / -1' }}>
                                    <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.85rem', color: '#64748b' }}>Descrição das Atividades</label>
                                    <textarea
                                        value={role.description || ''}
                                        onChange={(e) => updateField('roles', idx, 'description', e.target.value)}
                                        style={{ ...inputStyle, minHeight: '80px' }}
                                    />
                                </div>
                            </div>
                        </div>
                    ))}
                    {localData.roles.length === 0 && <p style={{ color: '#94a3b8', textAlign: 'center' }}>Nenhum cargo identificado.</p>}
                </div>
            )}

            {activeTab === 'riscos' && (
                <div>
                    <h3 style={sectionTitle}>Inventário de Riscos (PGR)</h3>
                    <p style={{ fontSize: '0.9rem', color: '#64748b', marginBottom: '1.5rem' }}>
                        Revise os riscos identificados para cada Grupo Homogêneo de Exposição (GHE).
                    </p>
                    {localInventory.map((risk, idx) => (
                        <div key={idx} style={{
                            padding: '1rem',
                            background: '#fff',
                            border: !risk.role_id ? '2px solid #ef4444' : '1px solid #e2e8f0',
                            borderRadius: '8px',
                            marginBottom: '1rem'
                        }}>
                            {!risk.role_id && (
                                <div style={{ color: '#ef4444', fontWeight: 'bold', marginBottom: '0.5rem', fontSize: '0.85rem' }}>
                                    ⚠️ Selecione um Cargo para este risco aparecer no documento
                                </div>
                            )}
                            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '1rem' }}>
                                <span style={{
                                    background: risk.type === 'Físico' ? '#dcfce7' : risk.type === 'Químico' ? '#fee2e2' : risk.type === 'Biológico' ? '#e0f2fe' : '#f3f4f6',
                                    color: risk.type === 'Físico' ? '#166534' : risk.type === 'Químico' ? '#991b1b' : risk.type === 'Biológico' ? '#075985' : '#374151',
                                    padding: '0.25rem 0.75rem', borderRadius: '999px', fontSize: '0.75rem', fontWeight: 'bold'
                                }}>
                                    {risk.type}
                                </span>
                                <button
                                    onClick={() => {
                                        const newInv = [...localInventory];
                                        newInv.splice(idx, 1);
                                        setLocalInventory(newInv);
                                    }}
                                    style={{ color: '#ef4444', background: 'none', border: 'none', cursor: 'pointer', fontSize: '0.85rem' }}
                                >
                                    🗑️ Remover
                                </button>
                            </div>

                            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                                {/* ORIGIN BADGE */}
                                {risk.origin_source && (
                                    <div style={{
                                        gridColumn: '1 / -1',
                                        marginBottom: '4px',
                                        fontSize: '0.75rem',
                                        color: '#6b7280',
                                        background: '#f3f4f6',
                                        display: 'inline-flex',
                                        alignItems: 'center',
                                        gap: '6px',
                                        padding: '4px 8px',
                                        borderRadius: '6px',
                                        width: 'fit-content',
                                        border: '1px solid #e5e7eb'
                                    }}>
                                        <span>🤖</span>
                                        <span>Motivo da Sugestão: <strong>{risk.origin_source}</strong></span>
                                    </div>
                                )}
                                <div style={{ gridColumn: '1 / -1' }}>
                                    <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.8rem', color: '#64748b' }}>Cargo Associado (GHE)</label>
                                    <select
                                        value={risk.role_id || ''}
                                        onChange={(e) => updateRisk(idx, 'role_id', e.target.value)}
                                        style={inputStyle}
                                    >
                                        <option value="">Selecione um cargo...</option>
                                        {localData.roles.map(r => (
                                            <option key={r.id} value={r.id}>{r.name} (CBO: {r.cbo})</option>
                                        ))}
                                    </select>
                                </div>
                                <div>
                                    <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.8rem', color: '#64748b' }}>Agente Nocivo (Hazard)</label>
                                    <input
                                        type="text"
                                        value={risk.hazard}
                                        onChange={(e) => updateRisk(idx, 'hazard', e.target.value)}
                                        style={inputStyle}
                                    />
                                </div>
                                <div>
                                    <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.8rem', color: '#64748b' }}>Fonte Geradora</label>
                                    <input
                                        type="text"
                                        value={risk.source}
                                        onChange={(e) => updateRisk(idx, 'source', e.target.value)}
                                        style={inputStyle}
                                    />
                                </div>

                                {/* QUANTITATIVE DATA SECTION */}
                                {risk.is_quantitative && (
                                    <div style={{ gridColumn: '1 / -1', background: '#f0f9ff', padding: '10px', borderRadius: '6px', border: '1px dashed #3b82f6', marginTop: '10px' }}>
                                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '10px' }}>
                                            <span style={{ fontSize: '1.2rem' }}>📊</span>
                                            <p style={{ margin: 0, fontSize: '0.9rem', fontWeight: 'bold', color: '#0369a1' }}>Avaliação Quantitativa (Agente Nocivo)</p>
                                        </div>
                                        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '10px' }}>
                                            <div>
                                                <label style={{ display: 'block', fontSize: '0.75rem', color: '#0369a1', marginBottom: '4px' }}>Medição Encontrada</label>
                                                <input
                                                    type="number"
                                                    placeholder="0.00"
                                                    value={risk.measurement_value || ''}
                                                    onChange={(e) => updateRisk(idx, 'measurement_value', e.target.value)}
                                                    style={{ width: '100%', padding: '6px', border: '1px solid #bae6fd', borderRadius: '4px' }}
                                                />
                                            </div>
                                            <div>
                                                <label style={{ display: 'block', fontSize: '0.75rem', color: '#0369a1', marginBottom: '4px' }}>Unidade</label>
                                                <input
                                                    type="text"
                                                    value={risk.measurement_unit || ''}
                                                    onChange={(e) => updateRisk(idx, 'measurement_unit', e.target.value)}
                                                    style={{ width: '100%', padding: '6px', border: '1px solid #bae6fd', borderRadius: '4px', background: '#f0f9ff' }}
                                                    readOnly={!!risk.measurement_unit}
                                                />
                                            </div>
                                            <div>
                                                <label style={{ display: 'block', fontSize: '0.75rem', color: '#0369a1', marginBottom: '4px' }}>Limite de Tolerância</label>
                                                <input
                                                    type="text"
                                                    value={risk.limit_tolerance || ''}
                                                    onChange={(e) => updateRisk(idx, 'limit_tolerance', e.target.value)}
                                                    style={{ width: '100%', padding: '6px', border: '1px solid #bae6fd', borderRadius: '4px', background: '#f0f9ff' }}
                                                    readOnly={!!risk.limit_tolerance}
                                                />
                                            </div>
                                        </div>
                                    </div>
                                )}
                                <div style={{ gridColumn: '1 / -1' }}>
                                    <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.8rem', color: '#64748b' }}>Meios de Propagação / Trajetória</label>
                                    <input
                                        type="text"
                                        value={risk.propagation || ''}
                                        onChange={(e) => updateRisk(idx, 'propagation', e.target.value)}
                                        style={inputStyle}
                                    />
                                </div>
                                <div>
                                    <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.8rem', color: '#64748b' }}>Danos à Saúde (Impact)</label>
                                    <input
                                        type="text"
                                        value={risk.impact || ''}
                                        onChange={(e) => updateRisk(idx, 'impact', e.target.value)}
                                        style={inputStyle}
                                    />
                                </div>
                                <div>
                                    <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.8rem', color: '#64748b' }}>Probabilidade (1-5)</label>
                                    <select
                                        value={risk.p || 1}
                                        onChange={(e) => {
                                            const p = parseInt(e.target.value);
                                            const s = risk.s || 1;
                                            const newInv = [...localInventory];
                                            newInv[idx].p = p;
                                            newInv[idx].level = p * s;
                                            setLocalInventory(newInv);
                                        }}
                                        style={inputStyle}
                                    >
                                        <option value="1">1 - Rara</option>
                                        <option value="2">2 - Pouco Provável</option>
                                        <option value="3">3 - Possível</option>
                                        <option value="4">4 - Provável</option>
                                        <option value="5">5 - Muito Provável</option>
                                    </select>
                                </div>
                                <div>
                                    <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.8rem', color: '#64748b' }}>Severidade (1-5)</label>
                                    <select
                                        value={risk.s || 1}
                                        onChange={(e) => {
                                            const s = parseInt(e.target.value);
                                            const p = risk.p || 1;
                                            const newInv = [...localInventory];
                                            newInv[idx].s = s;
                                            newInv[idx].level = p * s;
                                            setLocalInventory(newInv);
                                        }}
                                        style={inputStyle}
                                    >
                                        <option value="1">1 - Leve</option>
                                        <option value="2">2 - Baixa</option>
                                        <option value="3">3 - Moderada</option>
                                        <option value="4">4 - Alta</option>
                                        <option value="5">5 - Extrema</option>
                                    </select>
                                </div>
                                <div>
                                    <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.8rem', color: '#64748b' }}>Nível de Risco</label>
                                    <div style={{ ...inputStyle, background: '#eee' }}>
                                        {risk.level || (risk.p || 1) * (risk.s || 1)}
                                    </div>
                                </div>
                            </div>
                        </div>
                    ))}
                    <button
                        onClick={() => setLocalInventory([...localInventory, { type: 'Físico', hazard: '', source: '', impact: '', p: 1, s: 1, level: 1 }])}
                        style={{ width: '100%', padding: '0.75rem', background: '#f8fafc', border: '2px dashed #e2e8f0', borderRadius: '8px', color: '#64748b', cursor: 'pointer' }}
                    >
                        + Adicionar Novo Risco
                    </button>
                </div>
            )}

            {activeTab === 'exames' && (
                <div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <h3 style={sectionTitle}>Exames Médicos (PCMSO)</h3>
                        <button
                            onClick={handleRecalculateExams}
                            style={{
                                background: '#e0f2fe', color: '#0369a1', border: 'none', padding: '0.5rem 1rem',
                                borderRadius: '6px', cursor: 'pointer', fontSize: '0.85rem', fontWeight: 'bold'
                            }}
                        >
                            🔄 Recalcular com Base nos Riscos
                        </button>
                    </div>
                    {localData.medical_exams.map((exam, idx) => (
                        <div key={idx} style={{ padding: '1rem', background: '#f8fafc', borderRadius: '8px', marginBottom: '1rem', display: 'flex', gap: '1rem', alignItems: 'center' }}>
                            <div style={{ flex: 1 }}>
                                <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.8rem', color: '#64748b' }}>Exame</label>
                                <input
                                    type="text"
                                    value={exam.exam_type}
                                    onChange={(e) => updateField('medical_exams', idx, 'exam_type', e.target.value)}
                                    style={inputStyle}
                                />
                            </div>
                            <div style={{ flex: 1 }}>
                                <label style={{ display: 'block', marginBottom: '0.25rem', fontSize: '0.8rem', color: '#64748b' }}>Periodicidade</label>
                                <input
                                    type="text"
                                    value={exam.periodicidade}
                                    onChange={(e) => updateField('medical_exams', idx, 'periodicidade', e.target.value)}
                                    style={inputStyle}
                                />
                            </div>
                            <button
                                onClick={() => {
                                    const newData = { ...localData };
                                    newData.medical_exams.splice(idx, 1);
                                    setLocalData(newData);
                                }}
                                style={{ marginTop: '1.25rem', border: 'none', background: 'none', cursor: 'pointer' }}
                            >
                                🗑️
                            </button>
                        </div>
                    ))}
                    <button
                        onClick={() => {
                            const newData = { ...localData };
                            newData.medical_exams.push({ exam_type: '', periodicidade: 'Admissional/Periódico' });
                            setLocalData(newData);
                        }}
                        style={{ width: '100%', padding: '0.75rem', background: '#f8fafc', border: '2px dashed #e2e8f0', borderRadius: '8px', color: '#64748b', cursor: 'pointer' }}
                    >
                        + Adicionar Exame
                    </button>
                </div>
            )}

            {activeTab === 'cronograma' && (
                <div>
                    <h3 style={sectionTitle}>Plano de Ação</h3>
                    {localData.action_plan.map((action, idx) => (
                        <div key={idx} style={{ padding: '1rem', background: '#f8fafc', borderRadius: '8px', marginBottom: '1rem' }}>
                            <input
                                type="text"
                                value={action.description}
                                onChange={(e) => updateField('action_plan', idx, 'description', e.target.value)}
                                style={{ ...inputStyle, marginBottom: '0.5rem', fontWeight: 'bold' }}
                                placeholder="O que será feito?"
                            />
                            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '1rem' }}>
                                <input
                                    type="text"
                                    value={action.responsible || ''}
                                    onChange={(e) => updateField('action_plan', idx, 'responsible', e.target.value)}
                                    style={inputStyle}
                                    placeholder="Quem?"
                                />
                                <input
                                    type="text"
                                    value={action.deadline || ''}
                                    onChange={(e) => updateField('action_plan', idx, 'deadline', e.target.value)}
                                    style={inputStyle}
                                    placeholder="Quando?"
                                />
                                <select
                                    value={action.status || 'Pendente'}
                                    onChange={(e) => updateField('action_plan', idx, 'status', e.target.value)}
                                    style={inputStyle}
                                >
                                    <option value="Pendente">Pendente</option>
                                    <option value="Em andamento">Em andamento</option>
                                    <option value="Concluído">Concluído</option>
                                </select>
                            </div>
                        </div>
                    ))}
                    <button
                        onClick={() => {
                            const newData = { ...localData };
                            newData.action_plan.push({ description: '', responsible: '', deadline: '', status: 'Pendente' });
                            setLocalData(newData);
                        }}
                        style={{ width: '100%', padding: '0.75rem', background: '#f8fafc', border: '2px dashed #e2e8f0', borderRadius: '8px', color: '#64748b', cursor: 'pointer' }}
                    >
                        + Adicionar Ação
                    </button>
                </div>
            )}
        </div>
    );
};

export default ReviewView;
